### ISSUE TITLE
Next version checklist

### ISSUE THREAD

**Issue by typicode** [typicode/lowdb#192]
* [x] Rename `storages` to `adapters` to make it more obvious what they are
* [x] Refactor `adapters` to `function` or `class` instead of `object` @typicode https://github.com/typicode/lowdb/pull/196
* [x] Refactor `low` function to work with new adapters @typicode https://github.com/typicode/lowdb/pull/196
* [x] Upgrade all `dependencies` and `devDependencies`
* [ ] Catch error, if possible, when file is too big and parse/stringify fail, display a message like in https://github.com/typicode/lowdb/issues/180
* [x] Copy `.eslintrc` from https://github.com/typicode/json-server/blob/master/.eslintrc.js
* [x] Remove default storages, make `low()` memory only and `browser` config in `package.json`? Feedback welcome, related to https://github.com/typicode/lowdb/issues/189 and https://github.com/typicode/lowdb/issues/188 @typicode https://github.com/typicode/lowdb/pull/196

If you create a PR, please create one PR per item.

Work can be found on `0.17` branch.

**Comment by yeskunall** [comment]
[x] Rename `storages` to `adapters` to make it more obvious what they are (see [pull/194](https://github.com/typicode/lowdb/pull/194))

**Comment by yeskunall** [comment]
@typicode as for copying over the contents of `.eslintrc.js` from [typicode/json-server](https://github.com/typicode/json-server/blob/master/.eslintrc.js), wouldn't we need to make some changes before we do so? `json-server` uses `mocha` for tests, however, `lowdb` uses `tape` for tests. Let me know your thoughts.

**Comment by typicode** [comment]
@yeskunall good point, since `tape` doesn't have globals like `describe`, `it`, there should be no need to have a particular `env`. Also all the following dependencies should be there:

https://github.com/typicode/json-server/blob/master/package.json#L39-L46
https://github.com/typicode/json-server/blob/master/package.json#L53

**Comment by typicode** [comment]
Will work on `Refactor adapters to functions instead of objects, see example below`

**Comment by yeskunall** [comment]
@typicode expect a PR with the dependencies added to `package.json` and a port of the `.eslintrc` file.

> Will work on `Refactor adapters to functions instead of objects, see example below`

I'm not sure what you mean by that. Are you saying you're going to work on that one? 😓

**Comment by typicode** [comment]
Yes, I'm working on this one (sorry for the lack of details).

For the dependencies, I've just added https://greenkeeper.io so you may want to skip this one :) (I've marked it as done).

I've updated the list with the ones I'll do.

**Comment by yeskunall** [comment]
* [x] Copy .eslintrc from https://github.com/typicode/json-server/blob/master/.eslintrc.js 👍

**Comment by typicode** [comment]
It was easy to switch to `0.17` ;)

**Comment by yeskunall** [comment]
For the case when the file size is too large, do you just want to catch the error and display an error message? Not sure how this should be handled other than just emitting a message.

**Comment by typicode** [comment]
For the moment, I think I'll just postpone this one and release 0.17 as it is.

**Comment by yeskunall** [comment]
Sounds good!👌🏻
-- 

Kunall Banerjee

**Comment by typicode** [comment]
Released :) thanks again.
