### ISSUE TITLE
lowdb v2

### ISSUE THREAD

**Issue by typicode** [typicode/lowdb#302]
Hi 👋

I've created this issue to keep track of things to do for lowdb v2 (happening in the `next` branch). Feel free to pick tasks and create PR if you want. Just add a message below to avoid duplication of work.

Also small PRs that complete one task are easier to review and merge 👍 

And if you have any question, feel free to ask :)

Some of the goals of this version are:

* Make it simpler to use with TypeScript out of the box and simplify the work of the amazing people who are maintaining lowdb types definition on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) (huge thanks to them 🙏)
* Lower entry barrier by letting people use plain JS and make lodash optional for power users.
* Simplify adapters so that they do just one thing but still let third-party adapters with more features be used.

# TODO

* [x] Improve TypeScript support
* [x] Make it easier to use plain JS to query and modify data
* [x] Document usage with lodash
* [x] Create adapters interface
* [x] Create JSONFile and LocalStorage adapters
* [ ] Add third-party adapters in README (@typicode)
* [x] Add Memory and MemorySync adapters with tests 
  * Used for testing (https://github.com/typicode/lowdb/tree/next/examples#in-memory)
  * Read should return null
  * Write should do nothing
* [x] Verify `lib` output
  * It should work with Node 6+ and `require()`
  * Check that LocalStorage adapter can be imported using `import`
  * If not, maybe TypeScript config will need to be tweaked or Babel + TypeScript should be explored. In any case, I'd like to keep compiled files as small as possible.
* [x] Fix build error with localStorage not found
* [x] Prevent `*.test.ts` file to be output in `lib` (maybe a field in tsconfig?)
* [x] Modify server example to use await/async code for better readability (maybe switch to Koa as the await/async seems better out of the box)
* [ ] Fix bugs, typos, ... :)

Thank you 🙏

**Comment by ndr3w221** [comment]
make plugin support, i can, ill pull request

**Comment by typicode** [comment]
Hi @ndr3w221, 

Not sure how would it look like? Can you give a use case example with some code?

**Comment by ndr3w221** [comment]
db.use(somePluginObject)

Plugins can do: webview with control, remote control, shell, fixes and more
```
db.use(pluginJsonObject, {
 edit: true
 see: true
 ...
})
```

the second param from the code above ^ can be the perms that the plugin can do/access

**Comment by jesstelford** [comment]
@typicode Is the work on `v2` available anywhere? The [`next` branch](https://github.com/typicode/lowdb/tree/next) doesn't appear to exist on GitHub for this repo.

**Comment by LoiKos** [comment]
Hello, question about the example using Koa : why do you choose to not rely on Koa context ? I think the recommended way to add lowdb reference should use ` app.context.db = db `. Even if your example is totally working it's not really useful when your application start growing or could you add details on how to split files ?

**Comment by TheOPtimal** [comment]
> db.use(somePluginObject)
> 
> Plugins can do: webview with control, remote control, shell, fixes and more
> 
> ```
> db.use(pluginJsonObject, {
>  edit: true
>  see: true
>  ...
> })
> ```
> 
> the second param from the code above ^ can be the perms that the plugin can do/access

You can add plugins using lodash.

**Comment by typicode** [comment]
v2 has been published :partying_face:
if you've contributed to this release, you can use the Patron licence for v2.x :gift: 
Thank you :)
